//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bulochnaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id_Tovar { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] ImageTovar { get; set; }
        public Nullable<int> Id_review { get; set; }
    
        public virtual Reviews Reviews { get; set; }
    }
}
