//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bulochnaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewsTovar
    {
        public int ID { get; set; }
        public int Id_review { get; set; }
        public int Id_Tovar { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Reviews Reviews { get; set; }
    }
}
